backend:
  name: git-gateway
  branch: main
  squash_merges: true
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
  - name: "businesses"
    label: "Businesses"
    folder: "content/businesses"
    create: true
    identifier_field: "name"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Website URL", name: "url", widget: "string" }
      - { label: "Address", name: "address", widget: "text" }
      - label: "Languages"
        name: "languages"
        widget: "list"
        fields:
          - label: "Languages"
            name: "languages"
            widget: "relation"
            collection: "metadata"
            file: "languages"
            search_fields: ["languages.*.slug", "languages.*.name"]
            display_fields: ["languages.*.name"]
            value_field: "languages.*.slug"
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {
              label: "Tags",
              name: "tags",
              widget: "relation",
              collection: "metadata",
              file: "tags",
              search_fields: ["tags.*.name"],
              display_fields: ["tags.*.name"],
              value_field: "tags.*.name",
            }

      # - { label: "Location", name: "location", widget: "map", type: "location" }
  - name: "metadata"
    label: "Metadata"
    files:
      - name: "languages"
        label: "Languages"
        description: "Indigenous Languages"
        file: "content/_data/languages.json"
        extension: "json"
        fields:
          - name: "languages"
            label: "Languages"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Color", name: "color", widget: "color" }
      - name: "tags"
        label: "Tags"
        description: "Types of categories that businesses fall under"
        file: "content/_data/tags.json"
        extension: "json"
        fields:
          - name: "tags"
            label: "Tags"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
